main:
  - name: '<i class="fab fa-youtube"></i> Content'
    url: /content/
    weight: 2
  - name: '<i class="fas fa-cloud"></i> RStudio Cloud'
    url: "https://rstudio.cloud/spaces/126356/join?access_code=8xQWw%2FXR3sh636gTjzLknsoOX7VXHv0G%2Fix%2F8S1p"
    weight: 3
  - name: '<i class="fas fa-file-alt"></i> Q&A Doc'
    url: "https://docs.google.com/document/d/1eG_SlsY840bqrqEPasArb3L7K8SceS37RaANCrEnM0Q/edit?usp=sharing"
    weight: 4

content:
  - name: Overview
    weight: 1
  - name: Course content
    weight: 2
